export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const GET_RESTAURANT = "GET_RESTAURANT";
export const LOAD_RESTAURANTS = "LOAD_RESTAURANTS";
export const FAIL_RESTAURANTS = "FAIL_RESTAURANTS";
